### ISSUE TITLE
ContentPicker label even when hidden will still display after items are selected

### ISSUE THREAD

**Issue by michael-sumner** [10up/block-components#355]
### Describe the bug

Example component:

```jsx
<ContentPicker
	onPickChange={(pickedPost) => {
		setAttributes({ posts: pickedPost });
	}}
	mode="post"
	label={__('Select a post', 'mytheme')}
	placeholder={__('Select a post', 'mytheme')}
	contentTypes={contentTypes}
	content={posts}
	maxContentItems={1}
	hideLabelFromVision
	isOrderable={false}
	uniqueContentItems
/>
```

This will still output the label (although, as a generic `div` element with no CSS classname).
To fix this, currently this is the workaround:

```css
/* 10up/block-components styles */
:where(.editor-styles-wrapper) {

	/*
	 * Select the element outputted from the ContentPicker `label` prop,
	 * even if it does not have a CSS class for it.
	 * It will appear after all items are picked in the ContentPicker component.
	 */
	& .tenup-content-picker:has(div[class*="tenup-component-content-picker-"]) div:not(div[class]) {
		display: none;
	}
}
```

### Steps to Reproduce

Please see Bug descriptions.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
